Changed return code of bootstrap when in dry-run mode when changes need to be applied. Upgraded to latest zpresto version

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -40,6 +40,7 @@ debug() {
 check_and_replace() {
   FILE=$1
   TARGET=$2
+  CHECK_AND_REPLACE_RET=0
 
   #
   # If $FILE alrady exist, create a backup
@@ -71,6 +72,7 @@ check_and_replace() {
 
     if [ $DRYRUN -eq 1 ]; then
       cprint blue "   * DRY-RUN MODE: would have created a backup of ${TYPE} \`$(basename ${FILE})\` -> \`$(basename ${BAK_FILE})\`"
+      CHECK_AND_REPLACE_RET=1
     else
       debug "mv \"${FILE}\" \"${BAK_FILE}\""
       mv "${FILE}" "${BAK_FILE}"
@@ -78,7 +80,7 @@ check_and_replace() {
         cprint green "   * Created a backup of ${TYPE} \`$(basename ${FILE})\` -> \`$(basename ${BAK_FILE})\`"
       else 
         cprint red "   ! Error during backup creation. Abort."
-        return 1
+        return 2
       fi
     fi
     
@@ -89,6 +91,7 @@ check_and_replace() {
   #
   if [ $DRYRUN -eq 1 ]; then
     cprint blue "   * DRY-RUN MODE: would have created link: ${FILE} -> ${TARGET}"
+    CHECK_AND_REPLACE_RET=1
   else
     debug "ln -s \"${TARGET}\" \"${FILE}\""
     ln -s "${TARGET}" "${FILE}"
@@ -96,18 +99,18 @@ check_and_replace() {
       cprint green "   * Created link: ${FILE} -> ${TARGET}"
     else
       cprint red "   ! Error during link creation. Abort."
-      return 1
+      return 2
     fi
   fi
 
-  return 0
+  return $CHECK_AND_REPLACE_RET
 }
 
 
 bootstrap_module() {
   MODULE=$1
 
-  RET=0
+  BOOTSTRAP_MODULE_RET=0
   IFS=$'\r\n'
   for line in $(cat $MODULE/.bootstrap | grep -Ev '^\s*#'); do
     FILE=$(echo $line | awk '{print $1}')
@@ -118,7 +121,7 @@ bootstrap_module() {
     # If target is empty, there is an error
     if [ -z "${TARGET}" ]; then
       cprint red "   ! Target is empty. Did you forget it?"
-      return 1
+      return 2
     fi
     # If target is a dash, deduct it
     if [ "${TARGET}" = "-" ]; then
@@ -136,14 +139,20 @@ bootstrap_module() {
     # Check that target exist
     if [ ! -e "${TARGET}" ]; then
       cprint red "   ! Error: target does not exist ($TARGET)"
-      RET=1
+      BOOTSTRAP_MODULE_RET=2
       continue
     fi 
 
-    check_and_replace $FILE $TARGET || RET=1
+    check_and_replace $FILE $TARGET
+    BOOTSTRAP_MODULE_RET2=$?
+
+    # Higher return code, means higher error
+    if [[ $BOOTSTRAP_MODULE_RET2 -gt $BOOTSTRAP_MODULE_RET ]]; then
+      BOOTSTRAP_MODULE_RET=$BOOTSTRAP_MODULE_RET2
+    fi
   done
 
-  return $RET
+  return $BOOTSTRAP_MODULE_RET
 }
 
 #
@@ -185,6 +194,7 @@ fi
 
 
 ERRORS=0
+CHANGES_TO_APPLY=0
 
 # For each submodule, read .bootstrap file and do the bootstrap magic
 for module in $(ls .); do
@@ -197,12 +207,17 @@ for module in $(ls .); do
     cprint cyan "[ Entering in submodule : $(basename $module) ]"
 
     SUCCESS=0
+    LOCAL_CHANGES_TO_APPLY=0
     # Execute standard boostrap if .bootstrap file exists
     if [ -f $module/.bootstrap ]; then
       cprint cyan "% Calling standard bootstrap"
       bootstrap_module $module
-      if [ $? -eq 0 ]; then
+      RET=$?
+      if [ $RET -eq 0 ]; then
         SUCCESS=1
+      elif [ $RET -eq 1 ]; then
+        SUCCESS=1
+        LOCAL_CHANGES_TO_APPLY=1
       else 
         ERRORS=1
         cprint red "*** Some errors occured during standard bootstrap. Please review. ***"
@@ -215,8 +230,12 @@ for module in $(ls .); do
     if [ -x $module/bootstrap ]; then
       cprint cyan "% Executing custom bootstrap script"
       $module/bootstrap $DRYRUN_SWITCH
-      if [ $? -eq 0 ]; then
+      RET=$?
+      if [ $RET -eq 0 ]; then
         SUCCESS=1
+      elif [ $RET -eq 1 ]; then
+        SUCCESS=1
+        LOCAL_CHANGES_TO_APPLY=1
       else 
         ERRORS=1
         cprint red "*** Some errors occured during custom bootstrap. Please review. ***"
@@ -226,12 +245,21 @@ for module in $(ls .); do
     fi
 
     if [ $SUCCESS -eq 0 ]; then
-     cprint yellow "*** No bootstrap found in module ***"
-   else
-     cprint green "*** Module has been successfully bootstraped ***"
-   fi
-   echo
+      cprint yellow "*** No bootstrap found in module ***"
+    elif [ $LOCAL_CHANGES_TO_APPLY -eq 1 ]; then
+      cprint cyan "*** There are changes to be applyed ***"
+      CHANGES_TO_APPLY=1
+    else
+      cprint green "*** Module has been successfully bootstraped ***"
+    fi
+    echo
   fi
 done
 
-exit $ERRORS
+if [[ $CHANGES_TO_APPLY -eq 1 ]]; then
+  exit 1
+elif [[ $ERRORS -eq 1 ]]; then
+  exit 2
+fi
+
+exit 0
