Stop using getopt for arguments parsing.
Getopt is not portable. Use a bash compitable system to parse arguments.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -162,38 +162,18 @@ bootstrap_module() {
 #
 
 # Get arguments
-getopt -T > /dev/null 2>&1
-if [ $? -eq 4 ]; then
-  # GNU enhanced getopt is available
-  OPTS=$(getopt -o dhnH: --long debug,help,dry-run,home -n "$(basename $0)" -- "$@")
-  echo $OPTS
-  eval set -- "$OPTS"
-
-  while true; do
-    echo "\$1 = $1"
-    case "$1" in
-      -H|--home) HOMEDIR=$2 ; shift 2 ;;
-      -d|--debug) DEBUG=1 ;;
-      -n|--dry-run) DRYRUN=1 ; DRYRUN_SWITCH="-n" ; shift ;;
-      -h|--help) show_usage ; exit 0 ;;
-      --) shift ; break ;;
-      *) echo "Internal error!"; exit 1 ;;
-    esac
-  done
-else
-  # Original getopt is available. So use getopts instead
-  while getopts ":dhnH:" OPT; do
-    case "$OPT" in
-      H) HOMEDIR=$OPTARG ;;
-      d) DEBUG=1 ;;
-      n) DRYRUN=1 ; DRYRUN_SWITCH="-n" ;;
-      h) show_usage ; exit 0 ;;
-      \?) echo "Invalid option: -$OPTARG" >&2 ; exit 1 ;;
-      :) echo "Option -$OPTARG requires an argument." >&2 ; exit 1 ;;
-    esac
-  done
-fi
-
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -H|--home) HOMEDIR=$2 ; shift ;;
+    -d|--debug) DEBUG=1 ;;
+    -n|--dry-run) DRYRUN=1 ; DRYRUN_SWITCH="-n" ;;
+    -h|--help) show_usage ; exit 0 ;;
+    --) shift ; break ;;
+    -*) echo "Invalid parameter: $1" ; exit 1 ;;
+    *) echo "Invalid argument: $1" ; exit 1 ;;
+  esac
+  shift
+done
 
 ERRORS=0
 CHANGES_TO_APPLY=0
